# Generated by Django 3.1.4 on 2021-01-03 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_temperature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperature',
            name='temp',
            field=models.FloatField(),
        ),
    ]
