# Generated by Django 3.1.4 on 2021-01-05 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_auto_20210103_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperature',
            name='city',
            field=models.CharField(max_length=200),
        ),
    ]
